version: '3.7'

services:
  sample:
    container_name: srm-dex-fe
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: ['yarn', 'start']
