---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage
  name: srm-dex-fe-frontend-stage
  labels:
    project: srm-dex-fe
    kind: frontend
    app_env: stage
    environment: stage
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      project: srm-dex-fe
      kind: frontend
      app_env: stage
      environment: stage
  template:
    metadata:
      labels:
        project: srm-dex-fe
        kind: frontend
        app_env: stage
        environment: stage
    spec:
      containers:
      - name: srm-dex-fe-frontend-stage
        image: "{{ image_name }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 80
        resources:
          requests: 
            memory: "1G"
            cpu: "500m"
          limits:
            memory: "2G"
