---
project: ''   # project name on git
kind: ''      # subgroup on git
app_env: ''   # branch on git
namespace: '' # namespase on k8s

container:
  image: ''

deployment:
  maxSurge: 3
  probe_path: '/'

host_url: ''

affinity:
  role: ''
  environment: ''

podautoscaler:
  minReplicas: 3
  maxReplicas: 5
